import type { NextPage } from 'next';
import Head from 'next/head';

import { Cards } from '@components/cards/Cards';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Cards />
			</main>
		</>
	);
};

export default Home;
